#!/usr/bin/env python3
"""Clean up hardcoded fallback tool_feedback_explanation in session JSONL files.

Removes "tool_feedback_explanation" values that start with
"Continuing the current task.:" because they were generated by picoclaw
fallback logic, not by the AI.
"""

import json
import os
import sys
from pathlib import Path

PREFIX = "Continuing the current task.:"
DRY_RUN = "--dry-run" in sys.argv


def clean_file(path: Path) -> int:
    lines = path.read_text(encoding="utf-8").splitlines()
    modified = 0
    out_lines = []

    for line in lines:
        if not line.strip():
            out_lines.append(line)
            continue

        try:
            msg = json.loads(line)
        except json.JSONDecodeError:
            out_lines.append(line)
            continue

        changed = False
        for tc in msg.get("tool_calls", []):
            ec = tc.get("extra_content")
            if not ec:
                continue
            val = ec.get("tool_feedback_explanation", "")
            if val.startswith(PREFIX):
                ec["tool_feedback_explanation"] = ""
                changed = True

        if changed:
            modified += 1
            out_lines.append(json.dumps(msg, ensure_ascii=False))
        else:
            out_lines.append(line)

    if modified > 0 and not DRY_RUN:
        path.write_text("\n".join(out_lines) + "\n", encoding="utf-8")

    return modified


def main():
    sessions_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("sessions")
    if not sessions_dir.is_dir():
        print(f"Error: {sessions_dir} is not a directory")
        sys.exit(1)

    total = 0
    for p in sorted(sessions_dir.rglob("*.jsonl")):
        n = clean_file(p)
        if n > 0:
            print(f"{'[dry-run] ' if DRY_RUN else ''}{p}: {n} lines cleaned")
            total += n

    print(f"\nTotal: {total} lines cleaned across {sessions_dir}")
    if DRY_RUN:
        print("Dry run — no files were modified. Re-run without --dry-run to apply.")


if __name__ == "__main__":
    main()
